
services:
  api:
    build: .
    container_name: loan_service
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env.prod
    environment:
      - ENV=production
    restart: always

  db:
    image: postgres:15
    container_name: loan_service_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: loan_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: