
services:
  api:
    container_name: loan_service_dev
    image: golang:1.23.0-alpine
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: >
      sh -c "go get github.com/google/uuid@latest && go mod tidy && go install github.com/air-verse/air@latest && air"
    env_file:
      - .env.dev
    environment:
      - ENV=development
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: loan_service_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: loan_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: